### ISSUE TITLE
Let user import css instead

### ISSUE THREAD

**Issue by ScottEAdams** [cadenzah/videojs-react-enhanced#32]
## Is your feature request related to a problem? Please describe.
I was hoping to test this out on nextjs but sadly it throws the error:
```
./node_modules/video.js/dist/video-js.css
Global CSS cannot be imported from within node_modules.
Read more: https://err.sh/next.js/css-npm
Location: node_modules/videojs-react-enhanced/dist/index.es.js
```

## Describe the solution you'd like
In nextjs any global css must be loaded in _app.js so removing the video-js.css import would let me do so.

**Comment by cadenzah** [comment]
Thank you for reporting an issue for this library!

I see your point. I will remove the import of css in library, and let users import it themselves. It seems there isn't any reason to do it inside the library, and it will support better compatibility for use case like yours(Next.js).

+) Also will modify sample usage code on documentation

#### Reference
- [Next.js Error: CSS Imported by a Dependency](https://github.com/vercel/next.js/blob/master/errors/css-npm.md)
- [Video.js example with Next.js](https://github.com/vercel/next.js/tree/canary/examples/with-videojs)
