### ISSUE TITLE
Request: Add Callback Prop for `playing` event

### ISSUE THREAD

**Issue by rifaldhiaw** [cadenzah/videojs-react-enhanced#35]
Thanks in advance for your awesome suggestion of new feature for this library.

## Is your feature request related to a problem? Please describe.
If I am not mistaken, the `playing` event can be used to detect if the buffering process has ended.    
Here is the official description of the event:
> The media is no longer blocked from playback and has started playing.

I need that feature for tracking purposes. Right now, there is only `onWaiting` prop that can be used to detect if the video starting to buffer. Thanks

## Describe the solution you'd like
Add `onPlaying` props for `playing` event in videoJs player

## Describe alternatives you've considered
-

**Additional context**
-

**Comment by cadenzah** [comment]
Hi, and it's nice to see who uses this library!
I was late for checking you open this issue, and thank you for your work.
